name: Log4j2CancelMessage
version: '${project.version}'
main: com.github.eighty88.log4j2.CancelMessage
authors: [ eight_y_88 ]
description: Put a message that exploits the Log4J2 vulnerability as a secure message on the server side.
